import { MdSettings, MdHomeFilled, MdArticle, MdPeople, MdArchitecture, MdEmail, MdInfo, MdGroups, MdLocationPin, MdLocationCity, MdCategory, MdOutlineChat } from 'react-icons/md'

const hiddenDocTypes = listItem =>
  !['general', 'frontpage', 'project', 'person', 'contact', 'about', 'aboutPage', 'location', 'collaborator', 'client', 'category', 'language', 'people', 'newsArticle'].includes(listItem.getId())

export const structure = (S, context) =>
  S.list()
    .title('Innhold')
    .items([
      S.listItem()
        .title('Generelt')
        .icon(MdSettings)
        .child(
          S.editor()
            .title('Generelt')
            .id('general')
            .schemaType('general')
            .documentId('general')
        ),
      S.listItem()
        .title('Forside')
        .icon(MdHomeFilled)
        .child(
          S.editor()
            .title('Forside')
            .id('frontpage')
            .schemaType('frontpage')
            .documentId('frontpage')
        ),
      S.listItem()
        .title('Nyheter')
        .icon(MdArticle)
        .schemaType('newsArticle')
        .child(S.documentTypeList('newsArticle').title('Nyheter')),
      S.listItem()
        .title('Prosjekter')
        .icon(MdArchitecture)
        .schemaType('project')
        .child(S.documentTypeList('project').title('Prosjekter')),
      S.listItem()
        .title('Folk')
        .icon(MdPeople)
        .child(
          S.list()
            .id('articles')
            .title('Articles')
            .items(
              [
                S.listItem()
                  .title('Intro')
                  .icon(MdArticle)
                  .child(
                    S.editor()
                      .title('Intro')
                      .id('people')
                      .schemaType('people')
                      .documentId('people')
                  ),
                S.listItem()
                  .title('Liste over personer')
                  .schemaType('person')
                  .icon(MdPeople)
                  .child(
                    S.documentTypeList('person').title('Personer')
                  )
              ]
            )
        ),
      S.listItem()
        .title('Om')
        .icon(MdInfo)
        .child(
          S.list()
            .id('about')
            .title('Om')
            .items(
              [
                S.listItem()
                .title('Hovedside')
                .icon(MdInfo)
                .child(
                  S.editor()
                    .title('Hovedside')
                    .id('about')
                    .schemaType('about')
                    .documentId('about')
                ),
                S.divider(),
                S.listItem()
                  .title('Undersider')
                  .schemaType('aboutPage')
                  .child(S.documentTypeList('aboutPage').title('Undersider')),
                ]
          )
        ),
      S.listItem()
        .title('Kontakt')
        .icon(MdEmail)
        .child(
          S.editor()
            .title('Kontakt')
            .id('contact')
            .schemaType('contact')
            .documentId('contact')
        ),
      S.listItem()
        .title('Samarbeidspartnere')
        .icon(MdGroups)
        .schemaType('collaborator')
        .child(S.documentTypeList('collaborator').title('Samarbeidspartnere')),
      S.listItem()
        .title('Oppdragsgivere')
        .icon(MdLocationCity)
        .schemaType('client')
        .child(S.documentTypeList('client').title('Oppdragsgivere')),
      S.listItem()
        .title('Steder')
        .icon(MdLocationPin)
        .schemaType('location')
        .child(S.documentTypeList('location').title('Steder')),
      S.listItem()
        .title('Kategorier')
        .icon(MdCategory)
        .schemaType('category')
        .child(S.documentTypeList('category').title('Kategorier')),
      S.listItem()
        .title('Språk')
        .icon(MdOutlineChat)
        .schemaType('language')
        .child(S.documentTypeList('language').title('Språk')),
      // This returns an array of all the document types
      // defined in schema.js. We filter out those that we have
      // defined the structure above
      ...S.documentTypeListItems().filter(hiddenDocTypes)
    ])
